//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка доступа к бд в функции {0}, номер ошибки {1} (неверный логин/пароль).
        /// </summary>
        internal static string accessException {
            get {
                return ResourceManager.GetString("accessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0} при обращении к бд, номер ошибки {1} (не вышло подключиться к бд).
        /// </summary>
        internal static string cantConnectException {
            get {
                return ResourceManager.GetString("cantConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0} при обращении к бд, номер ошибки {1} (колонка не найдена).
        /// </summary>
        internal static string columnDoesntExistException {
            get {
                return ResourceManager.GetString("columnDoesntExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на server=localhost;port=3306;username=root;password=t-tAq$C45qw45;database=educationappdb.
        /// </summary>
        internal static string connectData {
            get {
                return ResourceManager.GetString("connectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0} при обращении к бд, номер ошибки {1} (бд не найдена).
        /// </summary>
        internal static string dbDoesntExistException {
            get {
                return ResourceManager.GetString("dbDoesntExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0} при обращении к бд, номер ошибки {1}.
        /// </summary>
        internal static string dbException {
            get {
                return ResourceManager.GetString("dbException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка FormatException в функции {0}.
        /// </summary>
        internal static string formatException {
            get {
                return ResourceManager.GetString("formatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка IndexOutOfRangeException обращения к элементу массива в функции {0}.
        /// </summary>
        internal static string indexOutOfRangeException {
            get {
                return ResourceManager.GetString("indexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка KeyNotFoundException получения ключа из словаря в функции {0}.
        /// </summary>
        internal static string keyNotFoundException {
            get {
                return ResourceManager.GetString("keyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0}, обращение к полю null, имя ошибки NullReferenceException.
        /// </summary>
        internal static string nullException {
            get {
                return ResourceManager.GetString("nullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка ResourceReferenceKeyNotFoundException при обращении к ресурсу приложения в функции {0}.
        /// </summary>
        internal static string resourceReferenceKeyNotFoundException {
            get {
                return ResourceManager.GetString("resourceReferenceKeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка в функции {0} при обращении к бд, номер ошибки {1} (таблица не найдена).
        /// </summary>
        internal static string tableDoesntExistException {
            get {
                return ResourceManager.GetString("tableDoesntExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка {0} в функции {1}.
        /// </summary>
        internal static string unknownException {
            get {
                return ResourceManager.GetString("unknownException", resourceCulture);
            }
        }
    }
}
